title: SUI 2018
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  ACM Sympusium on Spatial User Interfaces 2018
baseurl: "/2018" # the subpath of your site, e.g. /blog
url: "https://sui.acm.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum" "sunrise"
include: ["_pages"]

collections:
  archive:
    output: true
    permalink: /archive/:path/
  organization:
    output: true
    permalink: /organization/:path/

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
